//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CDResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CDResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.CDResource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Number.
        /// </summary>
        internal static string AccountNumber {
            get {
                return ResourceManager.GetString("AccountNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add my Language Details.
        /// </summary>
        internal static string AddMyLanguageDetails {
            get {
                return ResourceManager.GetString("AddMyLanguageDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add my software detail.
        /// </summary>
        internal static string AddMySoftwareDetail {
            get {
                return ResourceManager.GetString("AddMySoftwareDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adı.
        /// </summary>
        internal static string Adi {
            get {
                return ResourceManager.GetString("Adi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres.
        /// </summary>
        internal static string Adres {
            get {
                return ResourceManager.GetString("Adres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternatif Email.
        /// </summary>
        internal static string AlternatifEmail {
            get {
                return ResourceManager.GetString("AlternatifEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternatif Telefon.
        /// </summary>
        internal static string AlternatifTelefon {
            get {
                return ResourceManager.GetString("AlternatifTelefon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anasayfa.
        /// </summary>
        internal static string Anasayfa {
            get {
                return ResourceManager.GetString("Anasayfa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anlaşmalı Fiyat var mı?.
        /// </summary>
        internal static string AnlasmaliFiyatVarmi {
            get {
                return ResourceManager.GetString("AnlasmaliFiyatVarmi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Araçlar.
        /// </summary>
        internal static string Araclar {
            get {
                return ResourceManager.GetString("Araclar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Address.
        /// </summary>
        internal static string BankAddress {
            get {
                return ResourceManager.GetString("BankAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Name.
        /// </summary>
        internal static string BankName {
            get {
                return ResourceManager.GetString("BankName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bay.
        /// </summary>
        internal static string Bay {
            get {
                return ResourceManager.GetString("Bay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bayan.
        /// </summary>
        internal static string Bayan {
            get {
                return ResourceManager.GetString("Bayan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beneficiary Account Holder.
        /// </summary>
        internal static string BeneficiaryAccountHolder {
            get {
                return ResourceManager.GetString("BeneficiaryAccountHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beneficiary Address.
        /// </summary>
        internal static string BeneficiaryAddress {
            get {
                return ResourceManager.GetString("BeneficiaryAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beni Hatırla.
        /// </summary>
        internal static string BeniHatirla {
            get {
                return ResourceManager.GetString("BeniHatirla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bilingual Tongue.
        /// </summary>
        internal static string BilingualTongue {
            get {
                return ResourceManager.GetString("BilingualTongue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bireysel.
        /// </summary>
        internal static string Bireysel {
            get {
                return ResourceManager.GetString("Bireysel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cep Telefonu.
        /// </summary>
        internal static string CepTelefonu {
            get {
                return ResourceManager.GetString("CepTelefonu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate.
        /// </summary>
        internal static string Certificate {
            get {
                return ResourceManager.GetString("Certificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çevirmen Listesi.
        /// </summary>
        internal static string CevirmenListesi {
            get {
                return ResourceManager.GetString("CevirmenListesi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çıkış.
        /// </summary>
        internal static string Cikis {
            get {
                return ResourceManager.GetString("Cikis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cinsiyet.
        /// </summary>
        internal static string Cinsiyet {
            get {
                return ResourceManager.GetString("Cinsiyet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City and Country of the Bank.
        /// </summary>
        internal static string CityAndCountryOfTheBank {
            get {
                return ResourceManager.GetString("CityAndCountryOfTheBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        internal static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dahili.
        /// </summary>
        internal static string Dahili {
            get {
                return ResourceManager.GetString("Dahili", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dil.
        /// </summary>
        internal static string Dil {
            get {
                return ResourceManager.GetString("Dil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dil Listesi.
        /// </summary>
        internal static string DilListesi {
            get {
                return ResourceManager.GetString("DilListesi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dil Listesi görüntülenmektedir.
        /// </summary>
        internal static string DilListesiGoruntulenmektedir {
            get {
                return ResourceManager.GetString("DilListesiGoruntulenmektedir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dil Yönetimi.
        /// </summary>
        internal static string DilYonetimi {
            get {
                return ResourceManager.GetString("DilYonetimi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doğum Tarihi.
        /// </summary>
        internal static string DogumTarihi {
            get {
                return ResourceManager.GetString("DogumTarihi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Döküman.
        /// </summary>
        internal static string Dokuman {
            get {
                return ResourceManager.GetString("Dokuman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Döküman Ekle.
        /// </summary>
        internal static string DokumanEkle {
            get {
                return ResourceManager.GetString("DokumanEkle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Döküman Yönetimi.
        /// </summary>
        internal static string DokumanYonetimi {
            get {
                return ResourceManager.GetString("DokumanYonetimi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DTP (Desktop Publishing).
        /// </summary>
        internal static string DTPDesktopPublishing {
            get {
                return ResourceManager.GetString("DTPDesktopPublishing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ekle.
        /// </summary>
        internal static string Ekle {
            get {
                return ResourceManager.GetString("Ekle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail.
        /// </summary>
        internal static string EMail {
            get {
                return ResourceManager.GetString("EMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to European Accounts.
        /// </summary>
        internal static string EuropeanAccounts {
            get {
                return ResourceManager.GetString("EuropeanAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faks.
        /// </summary>
        internal static string Faks {
            get {
                return ResourceManager.GetString("Faks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiyat Listesi.
        /// </summary>
        internal static string FiyatListesi {
            get {
                return ResourceManager.GetString("FiyatListesi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gelen kutusu boş..
        /// </summary>
        internal static string GelenKutusuBos {
            get {
                return ResourceManager.GetString("GelenKutusuBos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gelen Mesajlar.
        /// </summary>
        internal static string GelenMesajlar {
            get {
                return ResourceManager.GetString("GelenMesajlar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genel Bilgiler.
        /// </summary>
        internal static string GenelBilgiler {
            get {
                return ResourceManager.GetString("GenelBilgiler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş.
        /// </summary>
        internal static string Giris {
            get {
                return ResourceManager.GetString("Giris", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glossary Creatin.
        /// </summary>
        internal static string GlossaryCreatin {
            get {
                return ResourceManager.GetString("GlossaryCreatin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gönder.
        /// </summary>
        internal static string Gonder {
            get {
                return ResourceManager.GetString("Gonder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gönderilen kutusu boş..
        /// </summary>
        internal static string GonderilenKutusuBos {
            get {
                return ResourceManager.GetString("GonderilenKutusuBos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gönderilen Mesajlar.
        /// </summary>
        internal static string GonderilenMesajlar {
            get {
                return ResourceManager.GetString("GonderilenMesajlar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to goruntulenmektedir..
        /// </summary>
        internal static string Goruntulenmektedir {
            get {
                return ResourceManager.GetString("Goruntulenmektedir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Göster.
        /// </summary>
        internal static string Goster {
            get {
                return ResourceManager.GetString("Goster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Günlük Kapasite.
        /// </summary>
        internal static string GunlukKapasite {
            get {
                return ResourceManager.GetString("GunlukKapasite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HedefDil.
        /// </summary>
        internal static string HedefDil {
            get {
                return ResourceManager.GetString("HedefDil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hedef Dil Yönetimi.
        /// </summary>
        internal static string HedefDilYonetimi {
            get {
                return ResourceManager.GetString("HedefDilYonetimi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBAN Number.
        /// </summary>
        internal static string IBANNumber {
            get {
                return ResourceManager.GetString("IBANNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I have.
        /// </summary>
        internal static string Ihave {
            get {
                return ResourceManager.GetString("Ihave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İl.
        /// </summary>
        internal static string Il {
            get {
                return ResourceManager.GetString("Il", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İlçe.
        /// </summary>
        internal static string Ilce {
            get {
                return ResourceManager.GetString("Ilce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İletişim Bilgileri.
        /// </summary>
        internal static string IletisimBilgileri {
            get {
                return ResourceManager.GetString("IletisimBilgileri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduce yourself briefly.
        /// </summary>
        internal static string IntroduceYourselfBriefly {
            get {
                return ResourceManager.GetString("IntroduceYourselfBriefly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İşlem.
        /// </summary>
        internal static string Islem {
            get {
                return ResourceManager.GetString("Islem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kapat.
        /// </summary>
        internal static string Kapat {
            get {
                return ResourceManager.GetString("Kapat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaydet.
        /// </summary>
        internal static string Kaydet {
            get {
                return ResourceManager.GetString("Kaydet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KaynakDil.
        /// </summary>
        internal static string KaynakDil {
            get {
                return ResourceManager.GetString("KaynakDil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaynak - Hedef Dil Yönetimi.
        /// </summary>
        internal static string KaynakHedefDilYonetimi {
            get {
                return ResourceManager.GetString("KaynakHedefDilYonetimi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kimden.
        /// </summary>
        internal static string Kimden {
            get {
                return ResourceManager.GetString("Kimden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konu.
        /// </summary>
        internal static string Konu {
            get {
                return ResourceManager.GetString("Konu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı.
        /// </summary>
        internal static string Kullanici {
            get {
                return ResourceManager.GetString("Kullanici", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Düzenle.
        /// </summary>
        internal static string KullaniciDuzenle {
            get {
                return ResourceManager.GetString("KullaniciDuzenle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı düzenlemek için kullanılır..
        /// </summary>
        internal static string KullaniciDuzenlemekIcinKullanilir {
            get {
                return ResourceManager.GetString("KullaniciDuzenlemekIcinKullanilir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Ekle.
        /// </summary>
        internal static string KullaniciEkle {
            get {
                return ResourceManager.GetString("KullaniciEkle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı eklemek için kullanılır. Kullanıcının diğer bilgilerini girmek için öncelikle kullanıcıyı sisteme kaydetmelisiniz. Daha sonra Kullanıcı Düzenle sayfasından diğer bilgilerini kaydedebilirsiniz..
        /// </summary>
        internal static string KullaniciEklemekIcinKullaniliKullanicininDigerBilgilerini {
            get {
                return ResourceManager.GetString("KullaniciEklemekIcinKullaniliKullanicininDigerBilgilerini", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Listesi.
        /// </summary>
        internal static string KullaniciListesi {
            get {
                return ResourceManager.GetString("KullaniciListesi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Tipi.
        /// </summary>
        internal static string KullaniciTipi {
            get {
                return ResourceManager.GetString("KullaniciTipi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kurumsal.
        /// </summary>
        internal static string Kurumsal {
            get {
                return ResourceManager.GetString("Kurumsal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linguistic Testing.
        /// </summary>
        internal static string LinguisticTesting {
            get {
                return ResourceManager.GetString("LinguisticTesting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen Seçiniz.
        /// </summary>
        internal static string LutfenSeciniz {
            get {
                return ResourceManager.GetString("LutfenSeciniz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Clients.
        /// </summary>
        internal static string MainClients {
            get {
                return ResourceManager.GetString("MainClients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesaj.
        /// </summary>
        internal static string Mesaj {
            get {
                return ResourceManager.GetString("Mesaj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesaj Gönder.
        /// </summary>
        internal static string MesajGonder {
            get {
                return ResourceManager.GetString("MesajGonder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min. Charge Amount.
        /// </summary>
        internal static string MinChargeAmount {
            get {
                return ResourceManager.GetString("MinChargeAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mother Tongue.
        /// </summary>
        internal static string MotherTongue {
            get {
                return ResourceManager.GetString("MotherTongue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muhasebe E-Mail.
        /// </summary>
        internal static string MuhasebeEmail {
            get {
                return ResourceManager.GetString("MuhasebeEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Müşteri.
        /// </summary>
        internal static string Musteri {
            get {
                return ResourceManager.GetString("Musteri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Müşteri Düzenle.
        /// </summary>
        internal static string MusteriDuzenle {
            get {
                return ResourceManager.GetString("MusteriDuzenle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Müşteri düzenlemek için kullanılır..
        /// </summary>
        internal static string MusteriDuzenlemekIcinKullanilir {
            get {
                return ResourceManager.GetString("MusteriDuzenlemekIcinKullanilir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Müşteri Ekle.
        /// </summary>
        internal static string MusteriEkle {
            get {
                return ResourceManager.GetString("MusteriEkle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Müşteri eklemek için kullanılır..
        /// </summary>
        internal static string MusteriEklemekIcinKullanilir {
            get {
                return ResourceManager.GetString("MusteriEklemekIcinKullanilir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Müşteri Listesi.
        /// </summary>
        internal static string MusteriListesi {
            get {
                return ResourceManager.GetString("MusteriListesi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Müşteri Tipi.
        /// </summary>
        internal static string MusteriTipi {
            get {
                return ResourceManager.GetString("MusteriTipi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ödeme Bilgileri.
        /// </summary>
        internal static string OdemeBilgileri {
            get {
                return ResourceManager.GetString("OdemeBilgileri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to only if really.
        /// </summary>
        internal static string OnlyIfReally {
            get {
                return ResourceManager.GetString("OnlyIfReally", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operating System.
        /// </summary>
        internal static string OperatingSystem {
            get {
                return ResourceManager.GetString("OperatingSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Details.
        /// </summary>
        internal static string OtherDetails {
            get {
                return ResourceManager.GetString("OtherDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to out of.
        /// </summary>
        internal static string OutOf {
            get {
                return ResourceManager.GetString("OutOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Details.
        /// </summary>
        internal static string PaymentDetails {
            get {
                return ResourceManager.GetString("PaymentDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paypal Account.
        /// </summary>
        internal static string PaypalAccount {
            get {
                return ResourceManager.GetString("PaypalAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paypal Email Address.
        /// </summary>
        internal static string PaypalEmailAddress {
            get {
                return ResourceManager.GetString("PaypalEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PO Kullanıyor mu?.
        /// </summary>
        internal static string PoKullaniyormu {
            get {
                return ResourceManager.GetString("PoKullaniyormu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posta Kodu.
        /// </summary>
        internal static string PostaKodu {
            get {
                return ResourceManager.GetString("PostaKodu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary Specialization.
        /// </summary>
        internal static string PrimarySpecialization {
            get {
                return ResourceManager.GetString("PrimarySpecialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profilim.
        /// </summary>
        internal static string Profilim {
            get {
                return ResourceManager.GetString("Profilim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProofReading.
        /// </summary>
        internal static string ProofReading {
            get {
                return ResourceManager.GetString("ProofReading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qualifications.
        /// </summary>
        internal static string Qualifications {
            get {
                return ResourceManager.GetString("Qualifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rates.
        /// </summary>
        internal static string Rates {
            get {
                return ResourceManager.GetString("Rates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating.
        /// </summary>
        internal static string Rating {
            get {
                return ResourceManager.GetString("Rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review.
        /// </summary>
        internal static string Review {
            get {
                return ResourceManager.GetString("Review", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review LQA (Language Quality Assurance).
        /// </summary>
        internal static string ReviewLQALanguageQualityAssurance {
            get {
                return ResourceManager.GetString("ReviewLQALanguageQualityAssurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review SME (Subject Matter Expert).
        /// </summary>
        internal static string ReviewSMESubjectMatterExpert {
            get {
                return ResourceManager.GetString("ReviewSMESubjectMatterExpert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sabit Telefon.
        /// </summary>
        internal static string SabitTelefon {
            get {
                return ResourceManager.GetString("SabitTelefon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Type.
        /// </summary>
        internal static string ServiceType {
            get {
                return ResourceManager.GetString("ServiceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre.
        /// </summary>
        internal static string Sifre {
            get {
                return ResourceManager.GetString("Sifre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şirket.
        /// </summary>
        internal static string Sirket {
            get {
                return ResourceManager.GetString("Sirket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şirket Adı.
        /// </summary>
        internal static string SirketAdi {
            get {
                return ResourceManager.GetString("SirketAdi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şirket Düzenle.
        /// </summary>
        internal static string SirketDuzenle {
            get {
                return ResourceManager.GetString("SirketDuzenle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şirket düzenlemek için kullanılır..
        /// </summary>
        internal static string SirketDuzenlemekIcinKullanilir {
            get {
                return ResourceManager.GetString("SirketDuzenlemekIcinKullanilir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şirket Ekle.
        /// </summary>
        internal static string SirketEkle {
            get {
                return ResourceManager.GetString("SirketEkle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şirket eklemek için kullanılır..
        /// </summary>
        internal static string SirketEklemekIcinKullanilir {
            get {
                return ResourceManager.GetString("SirketEklemekIcinKullanilir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şirket Listesi.
        /// </summary>
        internal static string SirketListesi {
            get {
                return ResourceManager.GetString("SirketListesi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şirket-Terminoloji Ekle.
        /// </summary>
        internal static string SirketTerminolojiEkle {
            get {
                return ResourceManager.GetString("SirketTerminolojiEkle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şirket-Terminoloji eklemek için kullanılır..
        /// </summary>
        internal static string SirketTerminolojiEklemekIcinKullanilir {
            get {
                return ResourceManager.GetString("SirketTerminolojiEklemekIcinKullanilir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şirket-Terminoloji List..
        /// </summary>
        internal static string SirketTerminolojiList {
            get {
                return ResourceManager.GetString("SirketTerminolojiList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şirket-Terminoloji Listesi.
        /// </summary>
        internal static string SirketTerminolojiListesi {
            get {
                return ResourceManager.GetString("SirketTerminolojiListesi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şirket-Teminoloji Listesi görüntülenmektedir..
        /// </summary>
        internal static string SirketTerminolojiListesiGoruntulenmektedir {
            get {
                return ResourceManager.GetString("SirketTerminolojiListesiGoruntulenmektedir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skype.
        /// </summary>
        internal static string Skype {
            get {
                return ResourceManager.GetString("Skype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software.
        /// </summary>
        internal static string Software {
            get {
                return ResourceManager.GetString("Software", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Lang..
        /// </summary>
        internal static string SourceLang {
            get {
                return ResourceManager.GetString("SourceLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Language.
        /// </summary>
        internal static string SourceLanguage {
            get {
                return ResourceManager.GetString("SourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soyadı.
        /// </summary>
        internal static string Soyadi {
            get {
                return ResourceManager.GetString("Soyadi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swift / BIC Code.
        /// </summary>
        internal static string SwiftBICCode {
            get {
                return ResourceManager.GetString("SwiftBICCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sworn Translation.
        /// </summary>
        internal static string SwornTranslation {
            get {
                return ResourceManager.GetString("SwornTranslation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Lang..
        /// </summary>
        internal static string TargetLang {
            get {
                return ResourceManager.GetString("TargetLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Language.
        /// </summary>
        internal static string TargetLanguage {
            get {
                return ResourceManager.GetString("TargetLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminology Extraction.
        /// </summary>
        internal static string TerminologyExtraction {
            get {
                return ResourceManager.GetString("TerminologyExtraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminoloji.
        /// </summary>
        internal static string Terminoloji {
            get {
                return ResourceManager.GetString("Terminoloji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminoloji Adı.
        /// </summary>
        internal static string TerminolojiAdi {
            get {
                return ResourceManager.GetString("TerminolojiAdi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminoloji Dökümanını Yükle.
        /// </summary>
        internal static string TerminolojiDokumaniniYukle {
            get {
                return ResourceManager.GetString("TerminolojiDokumaniniYukle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminoloji Listesi.
        /// </summary>
        internal static string TerminolojiListesi {
            get {
                return ResourceManager.GetString("TerminolojiListesi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminoloji Yönetimi.
        /// </summary>
        internal static string TerminolojiYonetimi {
            get {
                return ResourceManager.GetString("TerminolojiYonetimi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool Version.
        /// </summary>
        internal static string ToolVersion {
            get {
                return ResourceManager.GetString("ToolVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translation.
        /// </summary>
        internal static string Translation {
            get {
                return ResourceManager.GetString("Translation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translation Memory (TM) Management.
        /// </summary>
        internal static string TranslationMemoryTMManagement {
            get {
                return ResourceManager.GetString("TranslationMemoryTMManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translation Software.
        /// </summary>
        internal static string TranslationSoftware {
            get {
                return ResourceManager.GetString("TranslationSoftware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ülke.
        /// </summary>
        internal static string Ulke {
            get {
                return ResourceManager.GetString("Ulke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAT/TAX No.
        /// </summary>
        internal static string VATTAXNo {
            get {
                return ResourceManager.GetString("VATTAXNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vergi Dairesi.
        /// </summary>
        internal static string VergiDairesi {
            get {
                return ResourceManager.GetString("VergiDairesi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vergi Numarası.
        /// </summary>
        internal static string VergiNumarasi {
            get {
                return ResourceManager.GetString("VergiNumarasi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working Type.
        /// </summary>
        internal static string WorkingType {
            get {
                return ResourceManager.GetString("WorkingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yanıtla.
        /// </summary>
        internal static string Yanitla {
            get {
                return ResourceManager.GetString("Yanitla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Years of experience in translation.
        /// </summary>
        internal static string YearsOfExperienceInTranslation {
            get {
                return ResourceManager.GetString("YearsOfExperienceInTranslation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Mesaj.
        /// </summary>
        internal static string YeniMesaj {
            get {
                return ResourceManager.GetString("YeniMesaj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yetenek Bilgileri.
        /// </summary>
        internal static string YetenekBilgileri {
            get {
                return ResourceManager.GetString("YetenekBilgileri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yetkili Adsoyad.
        /// </summary>
        internal static string YetkiliAdsoyad {
            get {
                return ResourceManager.GetString("YetkiliAdsoyad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yetkili Cep Telefonu.
        /// </summary>
        internal static string YetkiliCepTelefonu {
            get {
                return ResourceManager.GetString("YetkiliCepTelefonu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yetkili E-Mail.
        /// </summary>
        internal static string YetkiliEmail {
            get {
                return ResourceManager.GetString("YetkiliEmail", resourceCulture);
            }
        }
    }
}
